    class IDViewModel {
  String? idmark,
      bloodgrp,
      allergy,
      photo,
      sign,
      issuedBy,
      phresi,
      date,
      validupto,
      pfoffi,
      phemergency,
      sno,
      idcardno,
      empno,
      empname,
      designation,
      location,
      dob,
      emp_name_hindi,
      designation_hindi,
      location_hindi;
  double? aadhar;

  IDViewModel(
      {required this.idmark,
      required this.bloodgrp,
      required this.allergy,
      required this.photo,
      required this.sign,
      required this.phresi,
      required this.date,
      required this.validupto,
      required this.pfoffi,
      required this.phemergency,
      required this.sno,
      required this.idcardno,
      required this.empno,
      required this.empname,
      required this.designation,
      required this.location,
      required this.dob,
      required this.issuedBy,
      required this.aadhar,
      required this.designation_hindi,
      required this.emp_name_hindi,
      required this.location_hindi});

  factory IDViewModel.fromJson(Map<String, dynamic> _insertWhatsNewJson) =>
      IDViewModel(
          idmark: _insertWhatsNewJson['ID_MARK'],
          bloodgrp: _insertWhatsNewJson['BLD_GRP'],
          allergy: _insertWhatsNewJson['ALLERGY'],
          photo: _insertWhatsNewJson['IMAGE'],
          sign: _insertWhatsNewJson['SIGN'],
          phresi: _insertWhatsNewJson['PH_RESI'],
          date: _insertWhatsNewJson['REQ_DATE'],
          validupto: _insertWhatsNewJson['VALID_UPTO'],
          pfoffi: _insertWhatsNewJson['PH_OFFI'],
          phemergency: _insertWhatsNewJson['PH_EMEGENCY'],
          sno: _insertWhatsNewJson['SNO'],
          issuedBy: _insertWhatsNewJson['ISSUED_BY'],
          empno: _insertWhatsNewJson['EMP_NO'],
          empname: _insertWhatsNewJson['EMP_NAME'],
          designation: _insertWhatsNewJson['DESIGNATION'],
          location: _insertWhatsNewJson['LOCATION'],
          dob: _insertWhatsNewJson['DATE_OF_BIRTH'],
          aadhar: _insertWhatsNewJson['AADHAR_NO'],
          idcardno: _insertWhatsNewJson['IDCARDNO'],
          emp_name_hindi: _insertWhatsNewJson['EMP_NAME_HINDI'],
          designation_hindi: _insertWhatsNewJson['DESIGNATION_HINDI'],
          location_hindi: _insertWhatsNewJson['LOCATION_HINDI']);
}
